spring.application.name=jiraclone

# Database connection
spring.datasource.url=jdbc:postgresql://localhost:5432/jiraclone
spring.datasource.username=postgres
spring.datasource.password=karikan
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
